/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Games;

import javax.swing.JOptionPane;

/**
 *
 * @author Andika Risky Septiawan
 */
public class Umum extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Umum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        a1d1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        d3 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        d2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        d4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        a2 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        d5 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        c2d6 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        a3e3 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        a4 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        a6f5 = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        a7 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        e4 = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        b1e6 = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        e5 = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        b2 = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        b3 = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        c3 = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        c4 = new javax.swing.JTextPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        c1 = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        f6 = new javax.swing.JTextPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        e1 = new javax.swing.JTextPane();
        jScrollPane22 = new javax.swing.JScrollPane();
        e2 = new javax.swing.JTextPane();
        jScrollPane23 = new javax.swing.JScrollPane();
        f1 = new javax.swing.JTextPane();
        jScrollPane24 = new javax.swing.JScrollPane();
        f3 = new javax.swing.JTextPane();
        jScrollPane25 = new javax.swing.JScrollPane();
        f2 = new javax.swing.JTextPane();
        jScrollPane26 = new javax.swing.JScrollPane();
        f4 = new javax.swing.JTextPane();
        jScrollPane27 = new javax.swing.JScrollPane();
        c5 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane28 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        tbMendatar = new javax.swing.JTextPane();
        btnMendatar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane30 = new javax.swing.JScrollPane();
        tbMenurun = new javax.swing.JTextPane();
        btnMenurun = new javax.swing.JButton();
        jScrollPane31 = new javax.swing.JScrollPane();
        a5 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a1d1.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        a1d1.setEnabled(false);
        jScrollPane1.setViewportView(a1d1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 37, -1));

        d3.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        d3.setEnabled(false);
        jScrollPane2.setViewportView(d3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 37, -1));

        d2.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        d2.setEnabled(false);
        jScrollPane3.setViewportView(d2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 37, -1));

        d4.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        d4.setEnabled(false);
        jScrollPane4.setViewportView(d4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 37, -1));

        a2.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        a2.setEnabled(false);
        jScrollPane5.setViewportView(a2);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 37, -1));

        d5.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        d5.setEnabled(false);
        jScrollPane6.setViewportView(d5);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 37, -1));

        c2d6.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        c2d6.setEnabled(false);
        jScrollPane7.setViewportView(c2d6);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 37, -1));

        a3e3.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        a3e3.setEnabled(false);
        jScrollPane8.setViewportView(a3e3);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 37, -1));

        a4.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        a4.setEnabled(false);
        jScrollPane9.setViewportView(a4);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 37, -1));

        a6f5.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        a6f5.setEnabled(false);
        jScrollPane10.setViewportView(a6f5);

        getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 37, -1));

        a7.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        a7.setEnabled(false);
        jScrollPane11.setViewportView(a7);

        getContentPane().add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 37, -1));

        e4.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        e4.setEnabled(false);
        jScrollPane12.setViewportView(e4);

        getContentPane().add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 37, -1));

        b1e6.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        b1e6.setEnabled(false);
        jScrollPane13.setViewportView(b1e6);

        getContentPane().add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 37, -1));

        e5.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        e5.setEnabled(false);
        jScrollPane14.setViewportView(e5);

        getContentPane().add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 37, -1));

        b2.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        b2.setEnabled(false);
        jScrollPane15.setViewportView(b2);

        getContentPane().add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 37, -1));

        b3.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        b3.setEnabled(false);
        jScrollPane16.setViewportView(b3);

        getContentPane().add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 37, -1));

        c3.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        c3.setEnabled(false);
        jScrollPane17.setViewportView(c3);

        getContentPane().add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 37, -1));

        c4.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        c4.setEnabled(false);
        jScrollPane18.setViewportView(c4);

        getContentPane().add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 37, -1));

        c1.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        c1.setEnabled(false);
        jScrollPane19.setViewportView(c1);

        getContentPane().add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 37, -1));

        f6.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        f6.setEnabled(false);
        jScrollPane20.setViewportView(f6);

        getContentPane().add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 37, -1));

        e1.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        e1.setEnabled(false);
        jScrollPane21.setViewportView(e1);

        getContentPane().add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 37, -1));

        e2.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        e2.setEnabled(false);
        jScrollPane22.setViewportView(e2);

        getContentPane().add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 37, -1));

        f1.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        f1.setEnabled(false);
        jScrollPane23.setViewportView(f1);

        getContentPane().add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 37, -1));

        f3.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        f3.setEnabled(false);
        jScrollPane24.setViewportView(f3);

        getContentPane().add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 37, -1));

        f2.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        f2.setEnabled(false);
        jScrollPane25.setViewportView(f2);

        getContentPane().add(jScrollPane25, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 37, -1));

        f4.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        f4.setEnabled(false);
        jScrollPane26.setViewportView(f4);

        getContentPane().add(jScrollPane26, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 37, -1));

        c5.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        c5.setEnabled(false);
        jScrollPane27.setViewportView(c5);

        getContentPane().add(jScrollPane27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 37, -1));

        jLabel1.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        jLabel1.setText("5");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        jLabel2.setText("1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        jLabel3.setText("4");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        jLabel4.setText("6");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        jLabel5.setText("2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        jLabel6.setText("Mendatar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Mendatar :\n1. Makan Pagi\n2. Penyebab Kebakaran\n3. Tidak berani\n\nMenurun :\n4. Hari sesudah senin\n5. Lawan surga\n6. Penyebab banjir");
        jTextArea1.setEnabled(false);
        jScrollPane28.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 300));

        tbMendatar.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        jScrollPane29.setViewportView(tbMendatar);

        getContentPane().add(jScrollPane29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 190, -1));

        btnMendatar.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        btnMendatar.setText("Cek");
        btnMendatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMendatarMouseClicked(evt);
            }
        });
        getContentPane().add(btnMendatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 80, -1));

        jLabel7.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        jLabel7.setText("3");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        jLabel8.setText("Menurun");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        tbMenurun.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        jScrollPane30.setViewportView(tbMenurun);

        getContentPane().add(jScrollPane30, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 190, -1));

        btnMenurun.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        btnMenurun.setText("Cek");
        btnMenurun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenurunMouseClicked(evt);
            }
        });
        getContentPane().add(btnMenurun, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 80, -1));

        a5.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        a5.setEnabled(false);
        jScrollPane31.setViewportView(a5);

        getContentPane().add(jScrollPane31, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 37, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMendatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMendatarMouseClicked
        // TODO add your handling code here:
        mendatar();
    }//GEN-LAST:event_btnMendatarMouseClicked

    private void btnMenurunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenurunMouseClicked
        // TODO add your handling code here:
        menurun();
    }//GEN-LAST:event_btnMenurunMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Umum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Umum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Umum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Umum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Umum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane a1d1;
    private javax.swing.JTextPane a2;
    private javax.swing.JTextPane a3e3;
    private javax.swing.JTextPane a4;
    private javax.swing.JTextPane a5;
    private javax.swing.JTextPane a6f5;
    private javax.swing.JTextPane a7;
    private javax.swing.JTextPane b1e6;
    private javax.swing.JTextPane b2;
    private javax.swing.JTextPane b3;
    private javax.swing.JButton btnMendatar;
    private javax.swing.JButton btnMenurun;
    private javax.swing.JTextPane c1;
    private javax.swing.JTextPane c2d6;
    private javax.swing.JTextPane c3;
    private javax.swing.JTextPane c4;
    private javax.swing.JTextPane c5;
    private javax.swing.JTextPane d2;
    private javax.swing.JTextPane d3;
    private javax.swing.JTextPane d4;
    private javax.swing.JTextPane d5;
    private javax.swing.JTextPane e1;
    private javax.swing.JTextPane e2;
    private javax.swing.JTextPane e4;
    private javax.swing.JTextPane e5;
    private javax.swing.JTextPane f1;
    private javax.swing.JTextPane f2;
    private javax.swing.JTextPane f3;
    private javax.swing.JTextPane f4;
    private javax.swing.JTextPane f6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane tbMendatar;
    private javax.swing.JTextPane tbMenurun;
    // End of variables declaration//GEN-END:variables

    private void mendatar() {
        if (tbMendatar.getText().trim().toLowerCase().equals("sarapan")) {
            a1d1.setText("S");
            a2.setText("A");
            a3e3.setText("R");
            a4.setText("A");
            a5.setText("P");
            a6f5.setText("A");
            a7.setText("N");
            tbMendatar.setText("");
        } else if (tbMendatar.getText().trim().toLowerCase().equals("api")) {
            b1e6.setText("A");
            b2.setText("P");
            b3.setText("I");
            tbMendatar.setText("");
        } else if (tbMendatar.getText().trim().toLowerCase().equals("takut")) {
            c1.setText("T");
            c2d6.setText("A");
            c3.setText("K");
            c4.setText("U");
            c5.setText("T");
            tbMendatar.setText("");
        } else if (tbMendatar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan jawaban Anda");
        } else {
            JOptionPane.showMessageDialog(null, "Jawaban Anda salah");
            tbMendatar.setText("");
        }
        vali_dasi();
    }

    private void menurun() {
        if (tbMenurun.getText().trim().toLowerCase().equals("selasa")) {
            a1d1.setText("S");
            d2.setText("E");
            d3.setText("L");
            d4.setText("A");
            d5.setText("S");
            c2d6.setText("A");
            tbMenurun.setText("");
        } else if (tbMenurun.getText().trim().toLowerCase().equals("neraka")) {
            e1.setText("N");
            e2.setText("E");
            a3e3.setText("R");
            e4.setText("A");
            e5.setText("K");
            b1e6.setText("A");
            tbMenurun.setText("");
        } else if (tbMenurun.getText().trim().toLowerCase().equals("sampah")) {
            f1.setText("S");
            f2.setText("A");
            f3.setText("M");
            f4.setText("P");
            a6f5.setText("A");
            f6.setText("H");
            tbMenurun.setText("");
        } else if (tbMenurun.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan jawaban Anda");
        } else {
            JOptionPane.showMessageDialog(null, "Jawaban Anda salah");
            tbMenurun.setText("");
        }
        vali_dasi();
    }

    private void vali_dasi() {
        if (a2.getText().equals("A") && b2.getText().equals("P") && c1.getText().equals("T")) {
            tbMendatar.setEnabled(false);
            btnMendatar.setEnabled(false);
        }
        
        if (d2.getText().equals("E") && e1.getText().equals("N") && f1.getText().equals("S")) {
            tbMenurun.setEnabled(false);
            btnMenurun.setEnabled(false);
        }
    }
}
